In [23]:
import numpy as np

In [24]:
pos = ['T','N','N','A','N','N','A','N','A','D','N']
nppos = np.array(pos)

In [25]:
nppos

array(['T', 'N', 'N', 'A', 'N', 'N', 'A', 'N', 'A', 'D', 'N'], 
      dtype='|S1')

In [26]:
indexA = np.where(nppos == 'A')
indexA = indexA[0]
indexA

array([3, 6, 8])

In [27]:
indexN = np.where(nppos == 'N')
indexN = indexN[0]
indexN

array([ 1,  2,  4,  5,  7, 10])

In [28]:
#remove single A
for idx in indexA:
    if idx+1 not in indexN:
        indexA = indexA[indexA != idx]
indexA

array([3, 6])

In [29]:
indexAN = np.concatenate((indexA,indexN),axis = 0)
indexAN

array([ 3,  6,  1,  2,  4,  5,  7, 10])

In [30]:
indexAN = np.sort(indexAN)
indexAN

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [31]:
term_list = []
tmp_word = ''
for idx in indexAN:
    tmp_word += pos[idx]
    if (idx+1) not in indexAN or pos[idx+1] == 'A':
        term_list.append(tmp_word)
        tmp_word = ''

In [32]:
term_list

['NN', 'ANN', 'AN', 'N']